---
title: From Vim to Emacs - Year Later
subtitle: Bit Of Retrospective On What I Came Through
description: There are many tutorials and articles about how to start with Emacs or how to switch to it from Vim. This is neither of these.
tags: emacs
---
#+AUTHOR: Marek Fajkus
#+EMAIL: marek.faj@gmail.com

It's been about a year since I've switched from my highly customized vim to Emacs as a default editor.
I have to admit it I had sometimes pretty tough times with Emacs especially at the beginnings.
You can imagine someone who gets so much used to his customized setup in one environment to sometimes
feel frustrated while making switch and starting new setup from scratch.
Anyway at the same time I've found it really beneficial and I believe it helped me reevaluate a lot of
thoughts on how interaction with computer and tools in general.
This article isn't meant in any sense to be tutorial to neither Emacs nor Vim but is rather
a reasoning about my experience and recapitulation of what I've learned during last year in this sense.
Can it really help someone? I don't know. But I still feel it's worth putting these ideas down.

* Why Would Anyone Possibly Want To Do This?

This sounds like a simple question, doesn't it? And indeed I believe It's simple question.
However I struggle to find a simple answer to it. Let me at least try to explain what drove me to all of this.

Generally I think there are some people who focus on creating things. I'm not really one of them - sorry.
Maybe I had been driven by passion for creating things in past and maybe it was reason I've started doing things I do.
Unfortunately I feel like I enjoy learning how things work rather then simply
using that knowledge for practical application. I also think it absolutely fine you might feel different yourself.
I get the point that tools are disruption[fn:1] from real problems. On the other hand some people are saying that it's
almost required to learn and using one of truly extensible editors (Vim/Emacs) to become real hacker[fn:2].
I don't want to do any of these points.

If you're really focus on things you're creating and simply can't / don't want to handle any additional complexity
some tool might bring just forget about this article right now and go do stuff you're really interested in.

As you can imagine I sent quite a some time learning and putting together [[https://github.com/turboMaCk/Dotfiles/blob/master/vimrc][my original Vim config]].
Why I did start over and switch to Emacs then? I think this is actually more philosophical than practical question.
Vim and Emacs both has own way to thinking about world. To some degree Vim is more *NIXy kind of tool which is cool.
It does one thing and it does it well - text manipulation is that thing my friends.
Yes learning curve is not the smoothest one but once you get to used to it it's fairly simple.
It's also extensible even though you're forced to use VimL[fn:3] what is sometimes strange.
However it's still pretty straight forward tool. Anyway it's also limited by design and its simplicity.
Vim itself is synchronous and it doesn't really supports much that goes beyond basic text editing well.
Even though there are projects like [[https://github.com/neovim/neovim][Neo Vim]] I think it' still fair to say that vim is design as ultimate tool for text manipulating and that's it.
Is it extensible? Sure but only to the point you're not trying to bend it way too much. That it starts to feel.. strange.

Emacs on the other hand is Lips runtime with interface for text editing. It's extensibility is insane.
As old joke you probably heard says: "Emacs is a great operating system lacking only decent text editor."
And there is some true to it. Think about it this way. Emacs is basic framework given to you so you can build
your own editor or anything you want in it. It's much more complicated than Vim is. For good and bad there are much more concepts
you need to learn to actually understand even small fragment of what Emacs can do.
Anyway for text editing addicts this is and ultimate tool. If you like text as I do you have all reasons to think considering Emacs as a tool of your choice.

*I've fall in love with Emacs view about the world.*

* Frustration

I have to admit I'm not one of these super smart people. Anyway I think I have good resistance to a pain.
I'm usually able to force myself through the hard path and somehow handle it without going crazy too much. Or maybe actually I have no problem with going crazy.
Anyway I have to admit this was hard. I was playing with Emacs for some time before I actually started to use it as main editor.
I've tried [[https://github.com/syl20bnr/spacemacs][Spacemacs]] distribution and wasn't really happy with it. I've started my configuration from scratch at least three times.
I've also used Emacs for about two weeks and then switched back to Vim for another several weeks simply because I was so frustrated
about stuff which doesn't work in a way I wanted.

One of the most painful things is when you really need to focus on solving some problem or delivering some shit and your
editor tries to telling you that you don't really know how to write. That sux pretty much.

I've managed to break it the hard way. I can tell you that I don't want to ever go through this process again.
The truth is I don't know if it was worth it. I know I'm happy now but I'm pretty sure I'm not objective at this point.
Anyway I have some advise especially for people who are coming to Emacs from Vim. Few lessons I've learned anyone should know up front.

** Learn First
You don't have to switch from day to day. Generally it's good idea to play with Emacs a bit first. And I mean pure Emacs.

** E-Lisp is Your Friend
If you're starting I think it's better to play with emacs-lisp rather than use it for working on your projects.
Using Emacs to do some work without knowing it will be only frustrating experience.
Using it to learn emacs-lisp helps you to stay focus and enjoy that experience.
Also elisp has amazing support up front. Let it be the measure for how you want to build your workflow for other languages.

** Don't be Too Much Evil
Evil mode is great. Anyway looking back I think it is really not a good idea to rely on it much especially at the beginning.
Evil is really Vim for Emacs but Emacs + Evil is much more than Vim inside Emacs. Don't ignore it.
You will have to learn some of the Emacs way sooner and later. Sooner is better.

** Try To Use Emacs In YOURS Workflow
There are so many cool plugins you want to try out I know. Anyway You can't possibly change your whole workflow in one day.
If you're using tmux try to use Emacs within tmux[fn:4]. If you're coming from GUI editor - use GUI and forget about terminal version.

** Don't Stick With It For Too Long Though...
Once you feel comfortable with Emacs in your workflow try to evolve it.

*** GUI Version Is Better
Really it is. Are you running Emacs with in terminal? What about running terminal within Emacs?

*** Magit is Awesome
I heard you like command line tools. That's great. I do too. Terminal should be the default way. Anyway give Magit a try.
It's advanced and you can switch to terminal any time you want.

*** Org Mode is Super Cool... But NOT Necessary
Org mode is so great. You want to learn it. Anyway if you're programmer I think it's fair to leave it.
You should focus on work first. Org mode is really simple. You will learn it in no time once you'll have time.

* After One Year

So I'm kind of celebrating my first year with Emacs. I really wanted to make some recap of what I've learned.
So I've [[https://github.com/turboMaCk/Dotemacs][rewrote my configuration to org-mode as literate program]]. I've also switched from ~use-package~
to [[https://github.com/cask/cask][Cask]] and [[https://github.com/rdallasgray/pallet][Pallet]]. Once again I've spend some of my free time just for setting things up.
This is what we OCD's do, right?

I also made few other changes / decisions based on my personal preferences:

** No More evil-leader
For some reason I don't feel like I'll need to use evil-leader anymore. I don't think it fits well to Emacs.
It was really helpful for making Emacs feel more like Vim at first but now I feel like I want to use Emacs way
of bindings rather then using leader.

** Goodbye NeoTree
You might know NERDTree plugin for Vim. It's largely popular among Vimmers. For every Vim plugin there is Emacs alternative.
However I was never really happy with Neotree for many reasons I don't want to discuss now. To remove this frustration
I simply forced myself not to use it by removing it. I'll rather use basics like ~dired~ or ~C-x C-f~ instead going forward.

* Are Emacs Users Better Programmers?

Hard to say. But you bet I believe they are as every other Emacs user do:D
Probably it's better to avoid any discussion like this right from start.
Anyway there are certain skill which comes hand in hand with going through process of setting up Emacs.
In the end your configuration is probably *the biggest project of your life time*. It will live and evolve with you.
I do believe it's worth understanding and spending time improving it.
But in the end it's all up to you. You can spent your time tweaking your own Emacs (or you can have social life:D)
You know what is important to you, don't you?

[fn:1] You can find many articles about tools as procrastination and similar.
- MPJ's video about why he uses basic text editor without extra config: https://www.youtube.com/watch?v=dIjKJjzRX_E
- J. Pabblo Fernández - Emacs is hurting clojure https://pupeno.com/2016/09/26/emacs-is-hurting-clojure/

[fn:2] Again there are dozens of examples about this topic.
- Perry Metzger - The Editor of The Lifetime talk https://www.youtube.com/watch?v=VADudzQGvU8

[fn:3] Actually Vim also supports plugins written in Python and other languages but these simply don't feel like first class citizens.

[fn:4] Check navigate.el for integration with Tmux. https://github.com/keith/evil-tmux-navigator
